name: Compile Java Backend
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: "17" }
      - name: Compile sources
        run: |
          mkdir -p out
          find app/src/main/java -name "*.java" > sources.txt
          if [ -s sources.txt ]; then javac -d out @sources.txt; else echo "No Java sources"; fi
      - name: Upload classes
        uses: actions/upload-artifact@v4
        with: { name: compiled-classes, path: out }
