name: Build Java Backend (Maven)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      # Optional: verify the project structure
      - name: Show project tree
        run: ls -la

      - name: Build with Maven (compile only)
        run: mvn -B -DskipTests clean compile

      # If you prefer to package the jar (often better)
      - name: Package JAR
        run: mvn -B -DskipTests package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifacts
          path: |
            target/*.jar
            target/classes/**
